### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by petrpatek** [apify/apify-eslint-config#1]
All peer dependencies should be probably installed as dependencies for simple usage.

**Comment by mnmkng** [comment]
Maybe we can do `eslint` as a peer dependency and all the others as dependencies. This way, we could (probably?) only have `eslint` and `eslint-config-apify` in our projects' `package.jsons` and everything else will be hidden inside this package.

I think `eslint` is needed as a peer dependency because IDEs and other tools might be checking for the presence of `eslint` in `package.json` to enable `eslint` specific features. I've encountered this with `jest`, where Webstorm would not show test integration tools unless `jest` was declared, even though it was installed in `node_modules`.

**Comment by petrpatek** [comment]
I am not sure if it is possible. I think that even if you require a configuration, `eslint` still searches for the plugins inside the project (first level) `node_modules`. I've made a branch  `feature/dependencies` with such a package.json, and I'm not able to link it, but the issue could be related to `npm link` not to the package itself.

**Comment by petrpatek** [comment]
I published two packages with two different variants. 

- With the `eslint` in peerDependencies [https://www.npmjs.com/package/@petrpatek/eslint-config-apify](link)
- Without peerDependencies [https://www.npmjs.com/package/@petrpatek/eslint-apify](link)
